#!/usr/bin/env bash
# make-pristine.sh <project> — rewind an executed Forge testbench project to a
# pristine, ready-to-run state. Run this ONCE (or after changing fixtures),
# then capture the result with snapshot.sh. Day-to-day resets use reset.sh.
#
# Pristine contract:
#   - store: tasks -> draft (summaries stripped), sprints -> planning,
#     bugs -> reported (summaries stripped), events emptied
#   - engineering: task folders keep TASK_PROMPT.md only; sprint folders keep
#     SPRINT_PLAN.md / SPRINT_REQUIREMENTS.md; bug folders keep nothing but
#     the folder; INDEX.md files regenerated by collate from the store
#   - .forge/cache, .forge/transcripts, enhancement-proposals wiped
#   - root run-artifacts (VALIDATION_REPORT.md, COMMIT-SUMMARY.json) removed;
#     BUG_REPORT*.md and sprint_requirements.md kept (they are fixtures)
#   - validate-store must pass before this script reports success
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT="${1:?usage: make-pristine.sh <project>}"
PROJ="$ROOT/$PROJECT"
STORE="$PROJ/.forge/store"
TOOLS="$PROJ/.forge/tools"

[ -d "$STORE" ] || { echo "× no store at $STORE" >&2; exit 1; }

echo "── make-pristine: $PROJECT"

# 1. Rewind store entities ──────────────────────────────────────────────────
python3 - "$STORE" <<'PY'
import json, glob, sys
store = sys.argv[1]

def rewind(pattern, status, drop=()):
    n = 0
    for f in sorted(glob.glob(f"{store}/{pattern}/*.json")):
        d = json.load(open(f))
        d["status"] = status
        for k in drop:
            d.pop(k, None)
        with open(f, "w") as fh:
            json.dump(d, fh, indent=2)
            fh.write("\n")
        n += 1
    print(f"  ✓ {pattern}: {n} -> {status}" + (f" ({', '.join(drop)} stripped)" if drop else ""))

rewind("tasks",   "draft",    drop=("summaries",))
rewind("sprints", "planning")
rewind("bugs",    "reported", drop=("summaries",))
PY

# 2. Empty the event log ────────────────────────────────────────────────────
rm -rf "$STORE/events"
mkdir -p "$STORE/events"
echo "  ✓ events emptied"

# 3. Wipe run state: cache, transcripts, enhancement-proposals ──────────────
rm -rf "$PROJ/.forge/cache" "$PROJ/.forge/transcripts" "$PROJ/.forge/enhancement-proposals"
mkdir -p "$PROJ/.forge/cache" "$PROJ/.forge/transcripts" "$PROJ/.forge/enhancement-proposals"
rm -f "$STORE/COLLATION_STATE.json"
echo "  ✓ cache / transcripts / enhancement-proposals wiped"

# 4. Prune engineering artifacts ────────────────────────────────────────────
python3 - "$PROJ" <<'PY'
import os, sys, glob

proj = sys.argv[1]
eng = os.path.join(proj, "engineering")

def prune(folder, keep):
    removed = 0
    for entry in os.listdir(folder):
        p = os.path.join(folder, entry)
        if os.path.isfile(p) and entry not in keep:
            os.remove(p)
            removed += 1
    return removed

n = 0
for sprint in sorted(glob.glob(f"{eng}/sprints/*/")):
    # sprint level: keep the plan + requirements (INDEX.md regenerated by collate)
    n += prune(sprint, keep={"SPRINT_PLAN.md", "SPRINT_REQUIREMENTS.md"})
    for task in sorted(glob.glob(f"{sprint}*/")):
        n += prune(task, keep={"TASK_PROMPT.md"})
for bug in sorted(glob.glob(f"{eng}/bugs/*/")):
    n += prune(bug, keep=set())
print(f"  ✓ engineering pruned: {n} execution artifacts removed")
PY

# 5. Remove root-level run artifacts (fixtures BUG_REPORT*.md / sprint_requirements.md stay)
rm -f "$PROJ/VALIDATION_REPORT.md" "$PROJ/COMMIT-SUMMARY.json"
echo "  ✓ root run-artifacts removed"

# 6. Re-collate KB indexes from the rewound store ───────────────────────────
if [ -f "$TOOLS/collate.cjs" ]; then
	(cd "$PROJ" && node "$TOOLS/collate.cjs" >/dev/null 2>&1) \
		&& echo "  ✓ collate: KB indexes regenerated" \
		|| echo "  ! collate failed (non-fatal) — INDEX.md files may be stale"
fi

# 7. Gate: store must validate ──────────────────────────────────────────────
if (cd "$PROJ" && node "$TOOLS/validate-store.cjs" --dry-run >/tmp/make-pristine-validate.log 2>&1); then
	echo "  ✓ validate-store: PASS"
else
	echo "× validate-store FAILED — state is NOT pristine. Log:" >&2
	cat /tmp/make-pristine-validate.log >&2
	exit 1
fi

echo "── pristine. Next: testbench/snapshot.sh $PROJECT"
